name: flutter_learning
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5  # Updated to the latest version
  english_words: ^4.0.0  # Add this line


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0  # Updated to the latest version

# Adding other dependencies based on the outdated output
dependency_overrides:
  characters: ^1.3.1   # Updated
  collection: ^1.19.0   # Updated
  material_color_utilities: ^0.12.0   # Updated
  meta: ^1.16.0   # Updated
  path: ^1.9.1   # Updated
  string_scanner: ^1.4.0   # Updated

  async: ^2.12.0   # Updated
  fake_async: ^1.3.2   # Updated
  leak_tracker: ^10.0.7   # Updated
  leak_tracker_flutter_testing: ^3.0.8   # Updated
  lints: ^5.1.0   # Updated
  matcher: ^0.12.17   # Updated
  stack_trace: ^1.12.0   # Updated
  test_api: ^0.7.3   # Updated
  vm_service: ^14.3.0   # Updated

flutter:
  uses-material-design: true
